/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codderbd.form;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FormValidation extends javax.swing.JFrame {

    /**
     * Creates new form FormValidation
     */
    public FormValidation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public boolean checkEmailValidaty(String email) {
        int atpos = email.indexOf("@");
        int dotpos = email.lastIndexOf(".");
        if (atpos > 1 && (dotpos - atpos) > 2 && dotpos < email.length()) {
            return true;
        } else {
            return false;
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1Id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3Age = new javax.swing.JTextField();
        jTextField4Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Round = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1Male = new javax.swing.JRadioButton();
        jRadioButton2Female = new javax.swing.JRadioButton();
        jCheckBox1HTML = new javax.swing.JCheckBox();
        jCheckBox2Java = new javax.swing.JCheckBox();
        jCheckBox3Swing = new javax.swing.JCheckBox();
        jComboBox1Round = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Comments = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1Display = new javax.swing.JTable();
        jButton1Exit = new javax.swing.JButton();
        jButton2Add = new javax.swing.JButton();
        jButton3ClearForm = new javax.swing.JButton();
        jButton4ClearTable = new javax.swing.JButton();
        jButton5WriteFromFile = new javax.swing.JButton();
        jLabel10Success = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                                             Form Validation");

        jLabel2.setText("ID");

        jTextField1Id.setText("0");

        jLabel3.setText("Name");

        jLabel4.setText("Age");

        jTextField3Age.setText("0");

        jLabel5.setText("Email");

        jLabel7.setText("Gender");

        Round.setText("Round");

        jLabel9.setText("Comments");

        buttonGroup1.add(jRadioButton1Male);
        jRadioButton1Male.setText("Male");

        buttonGroup1.add(jRadioButton2Female);
        jRadioButton2Female.setText("Female");

        jCheckBox1HTML.setText("HTML");

        jCheckBox2Java.setText("Java");

        jCheckBox3Swing.setText("Swing");

        jComboBox1Round.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your round", "Round - 40", "Round - 41", "Round - 42" }));

        jTextArea1Comments.setColumns(20);
        jTextArea1Comments.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Comments);

        jTable1Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Age", "Email", "Gender", "C.Course", "Group", "Title 8"
            }
        ));
        jScrollPane2.setViewportView(jTable1Display);

        jButton1Exit.setText("Exti");
        jButton1Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExitActionPerformed(evt);
            }
        });

        jButton2Add.setText("Add");
        jButton2Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2AddActionPerformed(evt);
            }
        });

        jButton3ClearForm.setText("Clear Form");
        jButton3ClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ClearFormActionPerformed(evt);
            }
        });

        jButton4ClearTable.setText("Clear Table");
        jButton4ClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ClearTableActionPerformed(evt);
            }
        });

        jButton5WriteFromFile.setText("Write From File");
        jButton5WriteFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5WriteFromFileActionPerformed(evt);
            }
        });

        jLabel11.setText("C.Course");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1Exit)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2Add)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3ClearForm))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4ClearTable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                        .addComponent(jButton5WriteFromFile))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Round)
                            .addComponent(jLabel11))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1Round, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1HTML)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2Java)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox3Swing))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1Male)
                                .addGap(40, 40, 40)
                                .addComponent(jRadioButton2Female))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4Email)
                            .addComponent(jTextField3Age)
                            .addComponent(jTextField1Id, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jTextField1Name))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel10Success, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jRadioButton1Male)
                            .addComponent(jRadioButton2Female))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jCheckBox1HTML)
                            .addComponent(jCheckBox2Java)
                            .addComponent(jCheckBox3Swing))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Round)
                            .addComponent(jComboBox1Round, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Exit)
                    .addComponent(jButton2Add)
                    .addComponent(jButton3ClearForm)
                    .addComponent(jLabel10Success, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5WriteFromFile)
                    .addComponent(jButton4ClearTable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2AddActionPerformed
        // TODO add your handling code here:
        if (jTextField1Id.getText().trim().length() < 4) {
            JOptionPane.showMessageDialog(null, "Enter your id At least 4 disits");
        } else if (jTextField1Name.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(null, "Enter your name at least 3 characters");
        } else if (Integer.parseInt(jTextField3Age.getText()) < 25
                || Integer.parseInt(jTextField3Age.getText()) > 100) {
            JOptionPane.showMessageDialog(null, "Enter your age between 25 to 100");
        } else if (!checkEmailValidaty(jTextField4Email.getText()) || jTextField4Email.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Enter your valid email");
        } else if (jRadioButton1Male.isSelected() == false && jRadioButton2Female.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Select your gender");
        } else if (!jCheckBox1HTML.isSelected() && !jCheckBox2Java.isSelected() && !jCheckBox3Swing.isSelected()) {
            JOptionPane.showMessageDialog(null, "select your course");
        } else if (jComboBox1Round.getItemAt(jComboBox1Round.getSelectedIndex()).trim().equalsIgnoreCase("Select your round")) {
            JOptionPane.showMessageDialog(null, "Select your round");
        } else if (jTextArea1Comments.getText().trim().length() < 10) {
            JOptionPane.showMessageDialog(null, "Enter at least 10 characters");
        } else {

            int id = Integer.parseInt(jTextField1Id.getText());
            String name = jTextField1Name.getText();
            int age = Integer.parseInt(jTextField3Age.getText());
            String email = jTextField4Email.getText();
            String gender = " ";
            if (jRadioButton1Male.isSelected()) {
                gender = jRadioButton1Male.getText();
            }
            if (jRadioButton2Female.isSelected()) {
                gender = jRadioButton2Female.getText();
            }
            String course = " ";
            if (jCheckBox1HTML.isSelected()) {
                course += jCheckBox1HTML.getText();
            }
            if (jCheckBox2Java.isSelected()) {
                course += jCheckBox2Java.getText();
            }
            if (jCheckBox3Swing.isSelected()) {
                course += jCheckBox3Swing.getText();
            }
            String round = jComboBox1Round.getItemAt(jComboBox1Round.getSelectedIndex());
            String comments = jTextArea1Comments.getText();

            String result = id + " , " + name + " " + age + " " + email + " " + gender + " " + course + " " + round + " " + comments;
            System.out.println(result);

            DefaultTableModel model = (DefaultTableModel) jTable1Display.getModel();
            Object[] row = new Object[8];
            row[0] = id;
            row[1] = name;
            row[2] = age;
            row[3] = email;
            row[4] = gender;
            row[5] = course;
            row[6] = round;
            row[7] = comments;
            model.addRow(row);

            Student s = new Student(id, name, age, email, gender, course, round, comments);
            List<Student> list = new ArrayList<>();
            list.add(s);
     
            try {
                Utils.writeToFile("Showkat", list);
            } catch (Exception e) {
                Object ex = null;
                Logger.getLogger(FormValidation.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                
            } catch (Exception e) {
                e.printStackTrace();
            }
           

            jLabel10Success.setText("Success");
        }
    }//GEN-LAST:event_jButton2AddActionPerformed

    private void jButton1ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ExitActionPerformed

    private void jButton4ClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ClearTableActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1Display.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton4ClearTableActionPerformed

    private void jButton3ClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ClearFormActionPerformed
        // TODO add your handling code here:
        jTextField1Id.setText("0");
        jTextField1Name.setText("");
        jTextField3Age.setText("0");
        jTextField4Email.setText("");
        buttonGroup1.clearSelection();
        jCheckBox1HTML.setSelected(false);
        jCheckBox2Java.setSelected(false);
        jCheckBox3Swing.setSelected(false);
        jComboBox1Round.setSelectedIndex(0);
        jTextArea1Comments.setText("");

    }//GEN-LAST:event_jButton3ClearFormActionPerformed

    private void jButton5WriteFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5WriteFromFileActionPerformed

        String columns[] = {"Id", "Name", "Age", "Email", "Gender", "Course", "Round", "Comments"};
        DefaultTableModel tableModel;
        tableModel = new DefaultTableModel(0, 8);
        tableModel.setColumnIdentifiers(columns);
        jTable1Display.setModel(tableModel);
        Utils.displayStudentDataFromFile("Showkat", tableModel);
    }//GEN-LAST:event_jButton5WriteFromFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormValidation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Round;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1Exit;
    private javax.swing.JButton jButton2Add;
    private javax.swing.JButton jButton3ClearForm;
    private javax.swing.JButton jButton4ClearTable;
    private javax.swing.JButton jButton5WriteFromFile;
    private javax.swing.JCheckBox jCheckBox1HTML;
    private javax.swing.JCheckBox jCheckBox2Java;
    private javax.swing.JCheckBox jCheckBox3Swing;
    private javax.swing.JComboBox<String> jComboBox1Round;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10Success;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1Male;
    private javax.swing.JRadioButton jRadioButton2Female;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1Display;
    private javax.swing.JTextArea jTextArea1Comments;
    private javax.swing.JTextField jTextField1Id;
    private javax.swing.JTextField jTextField1Name;
    private javax.swing.JTextField jTextField3Age;
    private javax.swing.JTextField jTextField4Email;
    // End of variables declaration//GEN-END:variables
}
